[program:webvirtcloud]
directory=/srv/webvirtcloud
command=/srv/webvirtcloud/venv/bin/gunicorn webvirtcloud.wsgi:application -c /srv/webvirtcloud/gunicorn.conf.py
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:novncd]
directory=/srv/webvirtcloud
command=/srv/webvirtcloud/venv/bin/python /srv/webvirtcloud/console/novncd
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:socketiod]
directory=/srv/webvirtcloud
command=/srv/webvirtcloud/venv/bin/python /srv/webvirtcloud/console/socketiod -d
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
